import { useEffect } from "react";
import { onForegroundMessage } from "@/lib/firebase";
import { registerPushToken } from "@/lib/fcm-register";
import { useAuthStore } from "@/store/auth";

export default function PwaRegister() {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;

    let fcmRegistration: ServiceWorkerRegistration | undefined;
    let registeredFor: string | null = null;
    let cancelled = false;

    const register = async () => {
      // Main PWA service worker (generated by VitePWA). It is NOT emitted in
      // dev (VitePWA devOptions disabled), so its absence must not block FCM.
      try {
        await navigator.serviceWorker.register("/sw.js", { scope: "/" });
      } catch (err) {
        console.warn(
          "[PWA] /sw.js not registered (likely dev without a PWA build):",
          err
        );
      }

      // Firebase Messaging service worker — pass full config via URL params.
      // Registered independently so FCM works even when /sw.js is unavailable.
      try {
        const p = new URLSearchParams({
          apiKey: "AIzaSyACABU-YpnQQ1rQBq5W-7r_itBYhPKWauk",
          authDomain: "madrasa-app-push-notification.firebaseapp.com",
          projectId: "madrasa-app-push-notification",
          storageBucket: "madrasa-app-push-notification.firebasestorage.app",
          messagingSenderId: "140700185441",
          appId: "1:140700185441:web:cec6824f02e0656025cb20",
        });
        const fcmSwUrl = `/firebase-messaging-sw.js?${p.toString()}`;
        console.log("[PWA] Registering FCM service worker...");
        fcmRegistration = await navigator.serviceWorker.register(
          fcmSwUrl,
          { scope: "/firebase-cloud-messaging-push-scope" }
        );
        // Wait for the worker to become active so getToken / push delivery
        // actually bind to THIS worker (not navigator.serviceWorker.ready,
        // which resolves to /sw.js and cannot handle FCM pushes).
        if (fcmRegistration.installing) {
          await (fcmRegistration.installing as unknown as { finished?: Promise<void> }).finished;
        }
        console.log("[PWA] FCM service worker registered:", fcmRegistration.scope);
      } catch (err) {
        console.error("[PWA] FCM service worker registration failed:", err);
      }
    };

    const registrationReady = register();

    // Register push token only on auth changes (not on initial mount —
    // avoids duplicate registration with RoleLoginPage after login).
    const ensureRegistered = async (userId: string | undefined) => {
      if (!userId) {
        registeredFor = null;
        return;
      }
      if (registeredFor === userId) return;
      registeredFor = userId;
      // Ensure the FCM SW is registered + active before requesting the token,
      // otherwise requestFcmToken falls back to navigator.serviceWorker.ready
      // (/sw.js) and the token can't receive FCM pushes.
      await registrationReady;
      if (cancelled) return;
      void registerPushToken(fcmRegistration);
    };

    const initial = useAuthStore.getState().user;
    if (initial) void ensureRegistered(initial.id);

    const unsubscribeAuth = useAuthStore.subscribe((state, prev) => {
      if (state.user?.id !== prev.user?.id) {
        void ensureRegistered(state.user?.id);
      }
    });

    // Show browser notifications for foreground FCM messages via the SW
    // (single notification path — avoids duplicate notifications when both
    // onMessage and the SW's onBackgroundMessage fire on focus changes)
    const unsubscribe = onForegroundMessage((payload) => {
      if (Notification.permission !== "granted") return;
      const title = payload.notification?.title || "Smart Madrasa";
      const targetUrl = payload.data?.url;
      const messageId = (payload as any).messageId || "";
      const tag = `fcm:${messageId || title}`;
      const options = {
        body: payload.notification?.body || "",
        icon: "/icons/icon-192.png",
        badge: "/icons/icon-192.png",
        tag,
        data: { ...(payload.data || {}), url: targetUrl },
      };

      // Route the notification to the FCM service worker (registered under a
      // separate scope), NOT navigator.serviceWorker.controller — the page is
      // controlled by /sw.js (VitePWA), which doesn't handle FCM_SHOW_NOTIFICATION.
      const fcmWorker = (fcmRegistration?.active ||
        fcmRegistration?.waiting ||
        navigator.serviceWorker.controller) as any;

      if (fcmWorker && typeof fcmWorker.postMessage === "function") {
        fcmWorker.postMessage({
          type: "FCM_SHOW_NOTIFICATION",
          title,
          options,
        });
        return;
      }

      // Fallback: show directly from the page if no SW is available.
      try {
        new Notification(title, {
          ...options,
          data: options.data,
        });
      } catch {
        /* Notification constructor unavailable */
      }
    });

    return () => {
      cancelled = true;
      unsubscribe?.();
      unsubscribeAuth();
    };
  }, []);

  return null;
}
