import { useEffect } from "react";
import { onForegroundMessage } from "@/lib/firebase";
import { registerPushToken } from "@/lib/fcm-register";
import { useAuthStore } from "@/store/auth";

export default function PwaRegister() {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;

    let fcmRegistration: ServiceWorkerRegistration | undefined;
    let registeredFor: string | null = null;

    const register = async () => {
      try {
        // Main PWA service worker (generated by VitePWA)
        await navigator.serviceWorker.register("/sw.js", { scope: "/" });

        // Firebase Messaging service worker — pass full config via URL params
        const p = new URLSearchParams({
          apiKey: "AIzaSyACABU-YpnQQ1rQBq5W-7r_itBYhPKWauk",
          authDomain: "madrasa-app-push-notification.firebaseapp.com",
          projectId: "madrasa-app-push-notification",
          storageBucket: "madrasa-app-push-notification.firebasestorage.app",
          messagingSenderId: "140700185441",
          appId: "1:140700185441:web:cec6824f02e0656025cb20",
        });
        const fcmSwUrl = `/firebase-messaging-sw.js?${p.toString()}`;
        console.log("[PWA] Registering FCM service worker...");
        fcmRegistration = await navigator.serviceWorker.register(
          fcmSwUrl,
          { scope: "/firebase-cloud-messaging-push-scope" }
        );
        console.log("[PWA] FCM service worker registered:", fcmRegistration.scope);
      } catch (err) {
        console.error("[PWA] Service worker registration failed:", err);
      }
    };

    void register();

    // Register push token only on auth changes (not on initial mount —
    // avoids duplicate registration with RoleLoginPage after login).
    const ensureRegistered = (userId: string | undefined) => {
      if (!userId) {
        registeredFor = null;
        return;
      }
      if (registeredFor === userId) return;
      registeredFor = userId;
      void registerPushToken(fcmRegistration);
    };

    const initial = useAuthStore.getState().user;
    if (initial) ensureRegistered(initial.id);

    const unsubscribeAuth = useAuthStore.subscribe((state, prev) => {
      if (state.user?.id !== prev.user?.id) {
        ensureRegistered(state.user?.id);
      }
    });

    // Show browser notifications for foreground FCM messages via the SW
    // (single notification path — avoids duplicate notifications when both
    // onMessage and the SW's onBackgroundMessage fire on focus changes)
    const unsubscribe = onForegroundMessage((payload) => {
      if (Notification.permission !== "granted") return;
      const title = payload.notification?.title || "Smart Madrasa";
      const targetUrl = payload.data?.url;
      const messageId = (payload as any).messageId || "";
      const tag = `fcm:${messageId || title}`;
      const controller = navigator.serviceWorker.controller as any;
      if (controller && typeof controller.postMessage === "function") {
        controller.postMessage({
          type: "FCM_SHOW_NOTIFICATION",
          title,
          options: {
            body: payload.notification?.body || "",
            icon: "/icons/icon-192.png",
            badge: "/icons/icon-192.png",
            tag,
            data: { ...(payload.data || {}), url: targetUrl },
          },
        });
      }
    });

    return () => {
      unsubscribe?.();
      unsubscribeAuth();
    };
  }, []);

  return null;
}
