import { useEffect } from "react";
import { onForegroundMessage } from "@/lib/firebase";
import { registerParentPushToken } from "@/lib/fcm-register";

export default function PwaRegister() {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;

    const register = async () => {
      try {
        // Main PWA service worker (generated by VitePWA)
        await navigator.serviceWorker.register("/sw.js", { scope: "/" });

        // Firebase Messaging service worker — pass full config via URL params
        const p = new URLSearchParams({
          apiKey: import.meta.env.VITE_FIREBASE_API_KEY || "",
          authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || "",
          projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || "",
          storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || "",
          messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
          appId: import.meta.env.VITE_FIREBASE_APP_ID || "",
        });
        const fcmSwUrl = `/firebase-messaging-sw.js?${p.toString()}`;
        console.log("[PWA] Registering FCM service worker...");
        const fcmRegistration = await navigator.serviceWorker.register(
          fcmSwUrl,
          { scope: "/firebase-cloud-messaging-push-scope" }
        );
        console.log("[PWA] FCM service worker registered:", fcmRegistration.scope);

        // Refresh parent FCM token on app load if already logged in
        void registerParentPushToken(fcmRegistration);
      } catch (err) {
        console.error("[PWA] Service worker registration failed:", err);
      }
    };

    void register();

    // Show browser notifications for foreground FCM messages
    const unsubscribe = onForegroundMessage((payload) => {
      if (Notification.permission !== "granted") return;
      const title = payload.notification?.title || "Smart Madrasa";
      const options: NotificationOptions = {
        body: payload.notification?.body || "",
        icon: "/icons/icon-192.png",
        badge: "/icons/icon-192.png",
        data: payload.data || {},
      };
      // eslint-disable-next-line no-new
      new Notification(title, options);
    });

    return () => {
      unsubscribe?.();
    };
  }, []);

  return null;
}
