import { useRef, useState, useCallback } from "react";
import { Download, FileImage, Printer, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import type {
  ClassReport, ClassReportRow, SubjectMeta, ClassReportConfig,
} from "@/lib/results-api";
import { GRADE_COLORS, TOTAL_GRADE_LABELS } from "@/lib/results-api";

function fmt(d?: string | null) {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

async function exportAsImage(el: HTMLElement, filename: string, format: "png" | "jpeg" = "png") {
  const html2canvas = (await import("html2canvas-pro")).default;
  const canvas = await html2canvas(el, { scale: 2, useCORS: true, backgroundColor: "#ffffff", logging: false });
  const blob = await new Promise<Blob | null>((res) => canvas.toBlob(res, format === "jpeg" ? "image/jpeg" : "image/png", 0.95));
  if (!blob) return;
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${filename}.${format}`;
  link.click();
  URL.revokeObjectURL(url);
}

async function exportAsPDF(el: HTMLElement, filename: string) {
  const [html2canvas, { jsPDF }] = await Promise.all([
    import("html2canvas-pro").then((m) => m.default),
    import("jspdf"),
  ]);
  const canvas = await html2canvas(el, { scale: 2, useCORS: true, backgroundColor: "#ffffff", logging: false });
  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pW = pdf.internal.pageSize.getWidth();
  const pH = pdf.internal.pageSize.getHeight();
  const ratio = canvas.width / canvas.height;
  const h = Math.min(pH, pW / ratio);
  pdf.addImage(imgData, "PNG", 0, 0, pW, h);
  pdf.save(`${filename}.pdf`);
}

function printTable(el: HTMLElement, title: string) {
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(`<!DOCTYPE html><html><head>
    <title>${title}</title>
    <style>
      * { box-sizing: border-box; margin: 0; padding: 0 }
      body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 11px; color: #111; background: #fff; padding: 30px 40px; }
      .header { text-align: center; margin-bottom: 20px; padding-bottom: 12px; border-bottom: 3px double #047857; }
      .header h1 { font-size: 18px; color: #047857; margin-bottom: 4px; letter-spacing: 1px; }
      .header .sub { font-size: 13px; color: #444; }
      .header .meta { font-size: 10px; color: #777; margin-top: 4px; }
      .stats { display: flex; justify-content: center; gap: 24px; margin-bottom: 16px; flex-wrap: wrap; }
      .stats div { text-align: center; padding: 6px 14px; background: #f0fdf4; border-radius: 6px; border: 1px solid #bbf7d0; }
      .stats .label { font-size: 9px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
      .stats .value { font-size: 16px; font-weight: 800; color: #047857; }
      table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
      thead { background: #047857; color: #fff; }
      th, td { border: 1px solid #d1d5db; padding: 5px 7px; text-align: center; vertical-align: middle; font-size: 10px; }
      th { font-weight: 700; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
      td:nth-child(2), td:nth-child(3) { text-align: left; }
      tr:nth-child(even) td { background: #f8fafc; }
      .rank-1 td { background: #fef9c3 !important; } .rank-2 td { background: #f1f5f9 !important; } .rank-3 td { background: #fef3c7 !important; }
      tfoot td { background: #f0fdf4 !important; font-weight: 700; border-top: 2px solid #047857; }
      .footer { text-align: center; font-size: 9px; color: #999; border-top: 1px solid #e5e7eb; padding-top: 10px; margin-top: 4px; }
      .footer span { color: #047857; font-weight: 700; }
      @media print { @page { margin: 15mm } body { padding: 0 } }
    </style></head><body>`);
  win.document.write(el.innerHTML);
  win.document.write(`<div class="footer">Generated by <span>Smart Madrasa</span> · ${new Date().toLocaleString("en-IN")}</div></body></html>`);
  win.document.close();
  win.focus();
  setTimeout(() => { win.print(); win.close(); }, 300);
}

interface Props {
  report: ClassReport;
  madrasaName?: string;
}

export function ClassResultTable({ report, madrasaName }: Props) {
  const { exam, class: cls, subjects, config, students, stats } = report;
  const tableRef = useRef<HTMLDivElement>(null);
  const [exporting, setExporting] = useState<"pdf" | "png" | "print" | null>(null);

  const filename = `${madrasaName ? madrasaName + " - " : ""}${cls.name} - ${exam.name}`;

  const doExport = useCallback(async (type: "pdf" | "png" | "print") => {
    if (!tableRef.current) return;
    setExporting(type);
    try {
      if (type === "print") {
        printTable(tableRef.current, filename);
      } else if (type === "pdf") {
        await exportAsPDF(tableRef.current, filename);
      } else {
        await exportAsImage(tableRef.current, filename, "png");
      }
    } finally {
      setExporting(null);
    }
  }, [filename]);

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 justify-end flex-wrap">
        {(["print", "pdf", "png"] as const).map((type) => (
          <button key={type} onClick={() => doExport(type)} disabled={!!exporting}
            className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg border border-gray-200 bg-white text-xs font-semibold text-gray-700 hover:bg-gray-50 disabled:opacity-50 transition-colors"
          >
            {exporting === type
              ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
              : type === "print" ? <Printer className="w-3.5 h-3.5" /> : <Download className="w-3.5 h-3.5" />
            }
            {type === "print" ? "Print" : type.toUpperCase()}
          </button>
        ))}
      </div>

      <div ref={tableRef} className="bg-white rounded-xl border border-gray-200 overflow-hidden" style={{ fontFamily: "'Segoe UI', Arial, sans-serif" }}>
        {/* Decorative header */}
        <div className="text-center px-6 pt-6 pb-4 border-b-4 border-emerald-700">
          <div className="w-16 h-0.5 bg-emerald-300 mx-auto mb-3" />
          {madrasaName && (
            <p className="text-emerald-700 text-xs font-bold uppercase tracking-[0.2em] mb-1">{madrasaName}</p>
          )}
          <h1 className="text-lg font-extrabold text-gray-900 tracking-tight">{exam.name}</h1>
          <p className="text-sm text-gray-600 mt-1">
            {cls.name}{cls.classTeacher ? <> · Class Teacher: {cls.classTeacher.name}</> : ""}
          </p>
          {exam.publishedDate && (
            <p className="text-[10px] text-gray-400 mt-0.5">Published: {fmt(exam.publishedDate)}</p>
          )}
          <div className="w-12 h-0.5 bg-emerald-300 mx-auto mt-3" />
        </div>

        {/* Stats bar */}
        <div className="grid grid-cols-5 divide-x divide-gray-100 border-b border-gray-100 text-center bg-emerald-50/30">
          {[
            { label: "Students", value: stats.totalStudents },
            { label: "Passed", value: stats.passedCount, color: "text-emerald-700" },
            { label: "Failed", value: stats.failedCount, color: "text-red-600" },
            { label: "Ranked", value: stats.rankedCount, color: "text-emerald-700" },
            { label: "Class Avg", value: `${stats.classAverage.toFixed(1)}%`, color: "text-teal-700" },
          ].map(({ label, value, color }) => (
            <div key={label} className="py-3 px-2">
              <div className={cn("text-lg font-extrabold", color ?? "text-gray-800")}>{value}</div>
              <div className="text-[9px] text-gray-500 uppercase tracking-wider mt-0.5">{label}</div>
            </div>
          ))}
        </div>

        {/* Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-emerald-700 text-white text-[10px] font-bold uppercase tracking-wide">
                <th className="px-3 py-2.5 text-center w-10">#</th>
                <th className="px-3 py-2.5 text-left">Reg No</th>
                <th className="px-3 py-2.5 text-left">Name</th>
                {subjects.map((s) => (
                  <th key={s.id} className="px-2 py-2.5 text-center min-w-24">
                    <div>{s.name}</div>
                    {!config.hideMarks && <div className="text-[9px] text-emerald-200 font-normal normal-case">/{s.maxMarks}</div>}
                  </th>
                ))}
                <th className="px-2 py-2.5 text-center">Total</th>
                <th className="px-2 py-2.5 text-center">%</th>
                <th className="px-2 py-2.5 text-center">Rank</th>
                <th className="px-2 py-2.5 text-center">Status</th>
                <th className="px-2 py-2.5 text-center">Grade</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {students.map((row, idx) => (
                <StudentRow key={row.student.id} row={row} idx={idx} subjects={subjects} config={config} />
              ))}
              {students.length === 0 && (
                <tr>
                  <td colSpan={subjects.length + 8} className="py-12 text-center text-sm text-gray-400">
                    No results computed yet. Run "Compute Grades" first.
                  </td>
                </tr>
              )}
            </tbody>
            {students.length > 0 && !config.hideMarks && (
              <tfoot>
                <tr className="bg-emerald-50 border-t-2 border-emerald-600 text-xs font-bold text-emerald-900">
                  <td colSpan={3} className="px-3 py-2.5">Class Average</td>
                  {subjects.map((s) => {
                    const vals = students
                      .map((r) => r.marks[s.id]?.score ?? null)
                      .filter((v): v is number => v !== null);
                    const avg = vals.length ? vals.reduce((a, b) => a + b, 0) / vals.length : null;
                    return <td key={s.id} className="px-2 py-2.5 text-center">{avg !== null ? avg.toFixed(1) : "—"}</td>;
                  })}
                  <td className="px-2 py-2.5 text-center">
                    {stats.classAverage > 0
                      ? ((stats.classAverage / 100) * (students[0]?.summary.totalMaxMarks ?? 0)).toFixed(1)
                      : "—"}
                  </td>
                  <td className="px-2 py-2.5 text-center">{stats.classAverage.toFixed(1)}%</td>
                  <td colSpan={3} />
                </tr>
              </tfoot>
            )}
          </table>
        </div>

        {/* Footer */}
        <div className="text-center py-3 border-t border-gray-100 text-[9px] text-gray-400">
          Generated by <span className="font-semibold text-emerald-600">Smart Madrasa</span> · {new Date().toLocaleString("en-IN")}
        </div>
      </div>
    </div>
  );
}

function StudentRow({ row, idx, subjects, config }: {
  row: ClassReportRow;
  idx: number;
  subjects: SubjectMeta[];
  config: ClassReportConfig;
}) {
  const { summary, student, marks } = row;
  const rankClass = summary.rank === 1 ? "bg-yellow-50/50" : summary.rank === 2 ? "bg-slate-50/60" : summary.rank === 3 ? "bg-amber-50/40" : "";

  return (
    <tr className={cn("hover:bg-gray-50 transition-colors", rankClass)}>
      <td className="px-3 py-2.5 text-center text-xs text-gray-500">{idx + 1}</td>
      <td className="px-3 py-2.5 text-xs font-mono text-gray-600">{student.adno}</td>
      <td className="px-3 py-2.5 font-medium text-gray-900">{student.name}</td>
      {subjects.map((s) => {
        const m = marks[s.id];
        return (
          <td key={s.id} className="px-2 py-2.5 text-center">
            {m ? (
              <div className="flex items-center justify-center gap-1.5">
                {!config.hideMarks && (
                  <span className={cn("text-sm font-semibold", m.isPassed === false ? "text-red-600" : "text-gray-800")}>
                    {m.score}
                  </span>
                )}
                {m.grade && (
                  <span className={cn("text-[10px] font-bold px-1.5 py-0.5 rounded", GRADE_COLORS[m.grade] ?? "text-gray-600 bg-gray-100")}>
                    {m.grade}
                  </span>
                )}
              </div>
            ) : (
              <span className="text-gray-300">—</span>
            )}
          </td>
        );
      })}
      <td className="px-2 py-2.5 text-center">
        {!config.hideMarks && summary.totalScore !== null ? (
          <span className="font-semibold text-gray-800">
            {summary.totalScore.toFixed(0)}
            <span className="text-xs text-gray-400 font-normal">/{summary.totalMaxMarks?.toFixed(0)}</span>
          </span>
        ) : "—"}
      </td>
      <td className="px-2 py-2.5 text-center font-semibold">
        {summary.totalPercentage !== null ? `${summary.totalPercentage.toFixed(1)}%` : "—"}
      </td>
      <td className="px-2 py-2.5 text-center font-bold text-gray-700">
        {summary.rank ?? "—"}
      </td>
      <td className="px-2 py-2.5 text-center">
        {summary.finalStatus ? (
          <span className={cn(
            "text-xs font-semibold px-2 py-0.5 rounded",
            summary.finalStatus === "PASSED" || summary.finalStatus === "PROMOTED"
              ? "bg-emerald-100 text-emerald-700"
              : "bg-red-100 text-red-700",
          )}>
            {summary.finalStatus === "PASSED" ? config.passedLabel
              : summary.finalStatus === "FAILED" ? config.failedLabel
              : summary.finalStatus === "PROMOTED" ? config.promotedLabel
              : config.withheldLabel}
          </span>
        ) : "—"}
      </td>
      <td className="px-2 py-2.5 text-center text-xs text-gray-600 font-medium">
        {summary.totalGrade ? (TOTAL_GRADE_LABELS[summary.totalGrade] ?? summary.totalGrade) : "—"}
      </td>
    </tr>
  );
}
